#!/bin/bash

rm -f corderda.buildrooms
rm -f corderda.adventure

gcc -o corderda.buildrooms corderda.buildrooms.c
gcc -o corderda.adventure corderda.adventure.c

./corderda.buildrooms
./corderda.adventure

#./cleanup
